openapi: "3.0.0"
info:
  title: Apple SignIn
  version: "1.0.0"

paths:
  /auth/keys:
    get:
      operationId: getKeys
      summary: Fetch Apple’s public key to verify the ID token signature.
      responses:
        '200':
          description: The request was successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JWKSet'

  /auth/token:
    post:
      operationId: token
      summary: Validate the authorization grant code with Apple to obtain tokens.
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/AppleSignInAuth"
      responses:
        '200':
          description: The request was successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppleSignInTokenResponse'
        '400':
          description: The server was unable to process the request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppleSignInError'


components:
  schemas:

    JWKSet:
      type: object
      required:
        - keys
      properties:
        keys:
          type: array
          description: An array that contains JSON Web Key objects.
          items:
             $ref: '#/components/schemas/JWKKey'

    JWKKey:
      type: object
      required:
        - kty
        - kid
        - use
        - alg
        - n
        - e
      properties:
        kty:
          type: string
          description: The key type parameter setting. This must be set to "RSA".
        kid:
          type: string
          description: A 10-character identifier key, obtained from your developer account.
        use:
          type: string
          description: The intended use for the public key.
        alg:
          type: string
          description: The encryption algorithm used to encrypt the token.
        n:
          type: string
          description: The modulus value for the RSA public key.
        e:
          type: string
          description: The exponent value for the RSA public key.

    AppleSignInAuth:
      type: object
      required:
        - client_id
        - client_secret
        - grant_type
        - code
        - redirect_uri
      properties:
        client_id:
          type: string
          description: The application identifier for your app.
        client_secret:
          type: string
          description: A secret generated as a JSON Web Token that uses the secret key generated by the WWDR portal.
        grant_type:
          type: string
          description: The grant type that determines how the client interacts with the server. For authorization code validation, use authorization_code. For refresh token validation requests, use refresh_token.
          enum:
            - authorization_code
            - refresh_token
        code:
          type: string
          description: The authorization code received from your application’s user agent. The code is single use only and valid for five minutes.
        redirect_uri:
          type: string
          description: The destination URI the code was originally sent to. It must include a domain name, and can’t be an IP address or localhost.

    AppleSignInTokenResponse:
      type: object
      required:
        - expires_in
        - id_token
        - refresh_token
        - token_type
      properties:
        expires_in:
          type: double
          description: The amount of time, in seconds, before the access token expires.
        id_token:
          type: string
          description: A JSON Web Token that contains the user’s identity information.
        refresh_token:
          type: string
          description: The refresh token used to regenerate new access tokens. Store this token securely on your server.
        token_type:
          type: string
          description: The type of access token. It will always be bearer.
          enum:
            - Bearer
        access_token:
          type: string
          description: (Reserved for future use) A token used to access allowed data. Currently, no data set has been defined for access.

    AppleSignInError:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: A string that describes the reason for the unsuccessful request. The string consists of a single allowed value.
          enum: 
            - invalid_request
            - invalid_client
            - invalid_grant
            - unauthorized_client
            - unsupported_grant_type
            - invalid_scope
