name: Compile and test

on: [pull_request]

jobs:
  macos:
    name: macos
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Switch Xcode version
      run: sudo xcode-select -s /Applications/Xcode_11.4.1.app/Contents/Developer
    - name: Run tests
      run: |
        make macos
        swift test
    - name: Generate linux tests
      run: |
        swift test --generate-linuxmain
        rm -rf .build
    - name: Cached auto-generate linux tests
      uses: actions/upload-artifact@v1
      with:
        name: generate-linuxmain
        path: .

  linux:
    name: linux
    needs: macos
    runs-on: ubuntu-latest

    steps:
    - name: Get auto-generate linux tests
      uses: actions/download-artifact@v1
      with:
        name: generate-linuxmain
        path: .
    - name: Remove generated artifact
      uses: geekyeggo/delete-artifact@v1
      with:
        name: generate-linuxmain
        failOnError: false
    - name: Run tests
      run: |
        sudo make linux
        swift test
